//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> CostPrise { get; set; }
        public Nullable<bool> StopList { get; set; }
        public Nullable<int> IDTypeofdish { get; set; }
    
        public virtual Typeofdish Typeofdish { get; set; }
    }
}
